language: shell
script: echo "hello"
before_script: echo "going to build"
after_script: echo "build sucessfull"
notifications:
  slack: nexxiscarebarcotalk:PCBxwVZM8bgAAJtMEJwDrjsG
  on_success: always  
  template:
    - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
    - "Execution time: *%{duration}*"
    - "Message: %{message}"  
